# NumPy

## Installing NumPy

In [ ]:
pip install numpy  

## Importing NumPy

In [7]:
#to import numpy library and alias name = np
import numpy as np                                                                              

# Array

In [6]:
arr = np.array((1,2,3,4))
print(arr)                                                                                                                               # 1d array

[1 2 3 4]


In [17]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)                                                                                                                            # 3*3 (2d array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)                                                                                                           #to check dimension of array

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [9]:
a = np.array([1,2,3,4])
np.save('outfile',a)                                                                                                       #saving to resuse the code
b = np.load('outfile.npy')                                                                                                 #loading to reuse the code
print(b)

[1 2 3 4]


In [18]:
arr =  np.arange(1,10,2)                                                                #start=1,stop=10(10 not included),step=2 ==> arr=[1,3,5,7,9]
print("elements of array:",arr)
arr1 = arr[np.array([4,0,1,2,3])]                                                #arr1 = element of arr at index position 4,0,1,2,3 ==> arr1=[9,1,3,5,]
print("indexed elements of array arr:", arr1)

elements of array: [1 3 5 7 9]
indexed elements of array arr: [9 1 3 5 7]


In [8]:
arr1 = np.arange(4)                                                                                   #start=0,stop=4(4 not included) ==> arr=[0,1,2,3]
print("array arr1:",arr1)
print("element at index 0 in arr1: ", arr1[0])
print("element at index 1 in arr1: ", arr1[1])

array arr1: [0 1 2 3]
element at index 0 in arr1:  0
element at index 1 in arr1:  1


In [3]:
arr = np.arange(12)                                                               #start=0,stop=12(12 not included) ==> arr=[0,1,2,3,4,5,6,7,8,9,10,11]
arr1 = arr.reshape(3,4)                                                           #make arr1 dimension as 3*4, now arr matrix becomes of 3*4
print("array arr1: ",arr1)
print("element at eth row and eth column in arr1: ", arr1[0][0])
print("element at 1st row and 2nd column in arr1: ", arr1[1][2])

array arr1:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
element at eth row and eth column in arr1:  0
element at 1st row and 2nd column in arr1:  6


In [4]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0])
print("first array:\n ",a)
print("\n")
print("second array:\n  ",b)
print("\n")
print("first array + second array:\n ", a+b)                                                                            #no need of for loop in python 

first array:
  [[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


second array:
   [1. 2. 3.]


first array + second array:
  [[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [6]:
arr=np.arange(51)
arr1=arr.reshape(17,3)
print("minimum value:", np.amin(arr1), " maximum value:",  np.amax(arr1))
print("mean value:",  np.mean(arr1), "median value:",  np.median(arr1))
print("standard deviation:", np.std(arr1), "variance:", np.var(arr1))
print("average value:", np.average(arr1))

minimum value: 0  maximum value: 50
mean value: 25.0 median value: 25.0
standard deviation: 14.719601443879744 variance: 216.66666666666666
average value: 25.0
